### ISSUE TITLE
Sharing repository-like data

### ISSUE THREAD

**Issue by inssein** [yoshuawuyts/choo#112]
I am looking at a few functional and unidirectional web frameworks, but not clear on how common data is shared between components.

Say you have two components (ComponentA and ComponentB), and they both need data from a Tag's API. How could it be modelled such that the data can be shared?

The goal to abstract away the side effects into one repository-like "model" that can be re-used, and data could be synchronized with message passing (subscriptions?)

**Comment by yoshuawuyts** [comment]
Hey there; thanks for opening this issue.

I'm not quite sure what you mean by "a Tag's API", but have you by any chance looked at https://github.com/yoshuawuyts/choo/tree/master/examples/http ? - It shows how to do request data over HTTP and how to let it flow through the application once it's been received. In a real world scenario there would probably be way more components, but since they would be function calls, views can pass the state on them as arguments on each re-render. 

Does that answer your question? Cheers!

**Comment by inssein** [comment]
Ah I think I just understood how choo works. I was assuming that each view was tied to a model, but it seems more like each view gets the state of the whole application.

That raises other performance related questions, but I see the little blurb about morphdom.

**Comment by yoshuawuyts** [comment]
@inssein Yay, glad it made sense! - Can I go ahead and close this issue then?

**Comment by inssein** [comment]
thanks for the quick answer!
