### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by knownasilya** [yoshuawuyts/choo#128]
For a framework, documentation is very important, so making it as accessible as possible is also important. A single markdown file can only go so far, so I'm wondering if you've thought of setting up a proper website for docs/api?

There are a few nice options out there, like https://github.com/rstacruz/flatdoc

**Comment by yoshuawuyts** [comment]
Hey, thanks for opening this :sparkles: We def agree with you - that's why we've started building [the choo handbook](https://github.com/yoshuawuyts/workshop-choo) and I did a bit of work on creating [an actual website](http://yoshuawuyts.com/www-choo/) a couple of weeks back. Neither of which are finished, but we'd love for people to get involved with this!

The handbook is built using [minidocs](https://github.com/freeman-lab/minidocs), which in turn is built using `choo` - it shouldn't be too different from `flatdoc` I reckon (perhaps less polished, but we'll get there hah). Tl;Dr: working on it, all help is welcome! :sparkles:

**Comment by marshallswain** [comment]
When the FeathersJS team switched its docs to GitBook, we saw a huge boost in edits from the community.  You can see an example here: http://docs.feathersjs.com/.  We also like the automatic CD that builds the docs in five formats.  The web version does allow highlighting and discussion, but we decided to turn that off and keep the discussion in GitHub issues.

**Comment by yoshuawuyts** [comment]
I feel this is done now :sparkles: http://choo.io/ - handbook.choo.io is still a WIP tho, but that should be done soon I hope (fingers crossed)
