### ISSUE TITLE
AssertionError: barracks.store.start.send: cb should be a function -- in subscriptions

### ISSUE THREAD

**Issue by qzapaia** [yoshuawuyts/choo#137]
### Expected behavior
Let me execute send with two arguments

### Actual behavior
It throw and error and say me it need a third argument (cb)

### Steps to reproduce behavior
subscriptions: [
    (send, done) => {
      setInterval(() => {
      	send('app:add', { payload: 'dog?' }), 1000)
    },1000)
    }
  ]

**Comment by yoshuawuyts** [comment]
Hey, so you can't send multiple arguments in `send()` - when sending data from inside a `model` it expects exactly three arguments: the name of the action you're calling, the data you want to send, and finally a callback to handle errors through the global `onError()` hook. So if you want to send two values, you'd have to either send an array or object containing them.

To update your example:
```js
subscriptions: [
  (send, done) => {
    setInterval(() => {
      send('app:add', { payload: 'dog?', myOtherValue: 1000 }), (err) => {
        if (err) return done(err)
      })
    }, 1000)
  }
]
```
I hope this answers your question! :sparkles:

**Comment by HoverBaum** [comment]
Also stumbled upon this. Better documentation that you need to provide a callback here would be awesome. And what it is for. Just to add some weight here.

**Comment by traducer** [comment]
@yoshuawuyts, the example you just provided has a minor syntax error, you closed the send method before adding the error callback.
```js
subscriptions: [
  (send, done) => {
    setInterval(() => {
      send('app:add', { payload: 'dog?', myOtherValue: 1000 }), (err) => {
        if (err) return done(err)
      })
    }, 1000)
  }
]
```
should be
```js
subscriptions: [
  (send, done) => {
    setInterval(() => {
      send('app:add', { payload: 'dog?', myOtherValue: 1000 }, (err) => {
        if (err) return done(err)
      })
    }, 1000)
  }
]
```

Also since this example is almost exactly the same as the subscriptions example in the documentation, I feel it needs to be updated to include the error handler.

I made a pull request with these changes https://github.com/yoshuawuyts/choo/pull/139.

Also I added an update to the `send` documentation to include an optional callback handler `send(actionName, data[, callback])` since this needs to be addressed for any calls to `send` inside a model.

**Comment by yoshuawuyts** [comment]
@traducer oooh, yeah - thanks for that! :grin:
