### ISSUE TITLE
Add size badge

### ISSUE THREAD

**Issue by ngryman** [yoshuawuyts/choo#167]
Hi,

A small PR to advertise the size of your library dynamically using https://github.com/ngryman/badge-size, if you are interested.

Thanks!

**Comment by yoshuawuyts** [comment]
@ngryman hey, thanks for suggesting this! I tend to be a bit cautious on which badges we add, because there's def a thing like "too many badges" - this is part of the reason we removed the IRC one a couple of days ago. I feel like we're doing a pretty good job at communicating the file size at the moment so perhaps we don't need a badge.

So for me I don't feel we'd need this, but I'd be keen to hear other's opinions on this too. Thanks again!

**Comment by ngryman** [comment]
@yoshuawuyts hey, I can understand that. It's true that size is part of your *catch phrase*. So it may be redundant to add a badge for that. The only added value I could see is that it would display the exact gzip size. But again I is it really adapted to you? I don't know 😅.

On a side note, I have a question. Would you be interested in a service that compiles a graph of this size evolution of your library between releases? I'm thinking about a tiny project like this and would like to confirm if people could be interested in this.

Thanks!

**Comment by yoshuawuyts** [comment]
@ngryman hard to say - really depends on the resulting service hah. That said I do like keeping track of metrics, so as an idea it's def interesting - keen to see what you come up with :sparkles:

Hah, but seems we're in agreement the badge might not be the greatest addition. I'll close this issue for now then as the original premisse is answered (and we've got so many issues open, gotta keep 'em tidy hah) :grin:

**Comment by ngryman** [comment]
@yoshuawuyts Sure, thanks for your time! I will get back to you if I have something interesting to show 👍
