### ISSUE TITLE
Get all the routes registered

### ISSUE THREAD

**Issue by wcastand** [yoshuawuyts/choo#264]
Once i registered my routes for `app.router([..])`
It would be cool if we can get all the registered routes.
`app.routes()`

I made a metalsmith plugins to render static version of a choo app without loosing the dynamic front app. [github](https://github.com/Kilix/metalsmith-choo)

It still in early stages, but i can't get the routes so user had to specify them manually.
(He can make a single file for both, but it would be nice if we can juste get his routes directly from the app).

I don't know if i'm clear enough, don't hesitate do ask me anything or telling me if i ask this in the wrong place :/

**Comment by yoshuawuyts** [comment]
While useful I'd rather not include this by default because of the size it adds. You can already get the router by accessing [`app._router`](https://github.com/yoshuawuyts/choo/blob/master/index.js#L22) and then walking it using the [`sheet-router/walk` function](https://github.com/yoshuawuyts/sheet-router/blob/master/walk.js) - this should provide you with all the registered routes I reckon - perhaps not the most ergnomic API, but it does the job.

It would be cool to turn the "get all routes" function into a separate package, as we could then re-use it for [server-render#caching](https://github.com/yoshuawuyts/server-render#caching). Help would def be appreciated!

Does this answer your question?

**Comment by yoshuawuyts** [comment]
While useful I'd rather not include this by default because of the size it adds. You can already get the router by accessing [`app._router`](https://github.com/yoshuawuyts/choo/blob/master/index.js#L22) and then walking it using the [`sheet-router/walk` function](https://github.com/yoshuawuyts/sheet-router/blob/master/walk.js) - this should provide you with all the registered routes I reckon - perhaps not the most ergnomic API, but it does the job.

It would be cool to turn the "get all routes" function into a separate package, as we could then re-use it for [server-render#caching](https://github.com/yoshuawuyts/server-render#caching). Help would def be appreciated!

Does this answer your question?

**Comment by wcastand** [comment]
Hi,
Yeah, i will into sheet-router/walk for my app.

And i would love to help for the package.
Do you have any example for making this a separate package or it just a function that take the app as a parameter ?

Thank again :)

**Comment by alexandrebodin** [comment]
Hi,

We might just add a route object configuration handler into sheet-router or do sth like

```js
import chooObjectRouter from 'chooObjectRouter';
import choo from 'choo';
const app = choo();

const routes = {} // to specify
chooObjectRouter(routes, app);
```

**Comment by alexandrebodin** [comment]
Hi,

We might just add a route object configuration handler into sheet-router or do sth like

```js
import chooObjectRouter from 'chooObjectRouter';
import choo from 'choo';
const app = choo();

const routes = {} // to specify
chooObjectRouter(routes, app);
```

**Comment by yoshuawuyts** [comment]
@wcastand was thinking along the lines of:
```js
const getRoutes = require('get-wayfarer-routes')
const getRoutes = require('sheet-router/routes') // could be repackaged by sheet-router
const getRoutes = require('choo/routes') // could be repackaged by choo to take 'app'
const sheet = require('sheet-router')

const router = sheet([
  ['/', () => document.createElement('main')],
  ['/hey', () => document.createElement('div')]
])
const routes = getRoutes(router)
console.log(routes)
// => [ '/', '/hey' ]
```

does this make sense?

**Comment by wcastand** [comment]
the goal is to make like walk.js ?
Creating a 'get-wayfarer-routes' in wayfarer package and then just exposed it in sheet-router and choo ?

Or do you want 'get-wayfarer-routes' to be a completely separate package from wayfarer ?

**Comment by yoshuawuyts** [comment]
@wcastand actually perhaps making a PR to `wayfarer` might make the most sense; as traversing the data structure and finding the route seems like a good fit C:

**Comment by wcastand** [comment]
Just to let everyone know. A PR is actually in review for this.
https://github.com/yoshuawuyts/wayfarer/pull/47

**Comment by yoshuawuyts** [comment]
`sheet-router` now also has a `walk` function that can be used for this. https://github.com/yoshuawuyts/sheet-router/blob/master/walk.js - think this one's solved now (:
