### ISSUE TITLE
Refs?

### ISSUE THREAD

**Issue by tmcw** [yoshuawuyts/choo#278]
### Expected behavior

Using `onload={}` to get a reference to an element in order to modify it with a non-choo library will allow that library to modify the element without overwriting changes in the second pass.

### Actual behavior

The DOM is rewritten later.

### Steps to reproduce behavior

Full code to an example: https://gist.github.com/tmcw/0b443b065c10b636cf073cbf64e67110

This is a pattern that's familiar to me with React: I'm integrating with [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/), a library that expects to control a small part of the DOM tree - the same will hold for Leaflet, Mapbox.js, and all other mapping libraries I know of. In React, we use refs to do this. In choo, I assumed that `onload={}` would be the ticket, but I can't find any way to get choo to play nice with a library that does its own DOM manipulation.

**Comment by roobie** [comment]
Perhaps you'll find #250 useful.

**Comment by tmcw** [comment]
I'm very confused by #250 - there's [no code in cache-element](https://github.com/yoshuawuyts/cache-element/blob/master/index.js)

**Comment by yoshuawuyts** [comment]
@tmcw so the idea was to have someone else write the implementation, after I specced out the design. Kind of like a mentorship thing. I feel it's been taking a while now tho, and there's a def need for these elements to exist so I might just fast forward the process.

I have some crude implementations ready to be polished and then pushed, which I'll put up sometime tomorrow (CET) so you can progress on this, as I would very much want to unblock you and have a great time integrating widgets like mapbox.

Apologies for the confusion leading up to this; hope you've been having a pleasant time using choo otherwise :sparkles:

**Comment by yoshuawuyts** [comment]
@tmcw released `cache-element@1.1.0` - the `widget` function should be what you're looking for to integrate `mapbox` with `yo-yo/choo` https://github.com/yoshuawuyts/cache-element :sparkles: keen to hear your thoughts on it!

**Comment by yoshuawuyts** [comment]
This should be solved; gonna close this :sparkles: - lmk if you've got any further questions, always happy to help!
