### ISSUE TITLE
Expose a version property

### ISSUE THREAD

**Issue by ngryman** [yoshuawuyts/choo#287]
Hey,

After posting https://github.com/yoshuawuyts/choo-log/issues/22, I was thinking that it could be a good idea to expose a `version` property so that plugins or third party code can make good decisions when it comes to support older versions.

**Comment by yoshuawuyts** [comment]
Hey, I'm very sorry but I replied from email and somehow it didn't come through. I wrote this:
> Where would you imagine this property lives? I'm bringing this up because plugins don't have access to the
`app` instance itself, so reading properties from there would make for an odd API

**Comment by ngryman** [comment]
I would see two ways to access this property:

 - For app authors: `choo.version` would be perfect as they explicitly have to require `choo`.
 - For plugin authors: a new hook (i.e. `onInit`) that would have the version as argument.

**Comment by yoshuawuyts** [comment]
Where would you imagine this property lives? I'm bringing this up because
plugins don't have access to the
`app` instance itself, so reading properties from there would make for an
odd API

On Sat, Oct 22, 2016 at 6:25 PM Nicolas Gryman <notifications@github.com>
wrote:

Hey,

After posting yoshuawuyts/choo-log#22
<https://github.com/yoshuawuyts/choo-log/issues/22>, I was thinking that it
could be a good idea to expose a version property so that plugins or third
party code can make good decisions when it comes to support older versions.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yoshuawuyts/choo/issues/287>, or mute the thread

**Comment by yoshuawuyts** [comment]
https://github.com/yoshuawuyts/choo/pull/289

**Comment by yoshuawuyts** [comment]
On another note: I do like your proposal; I think it might be useful -
could you perhaps draft out in a bit more detail what'd go in `onInit()` ?

**Comment by ngryman** [comment]
@yoshuawuyts Sorry for the late. Well what about passing the application itself? So plugin authors can do whatever they want.

If so you could just set the `version` property on the application instance. So there is a unique access point to it. I don't know if this makes sense, but it could also allow multiple instances of different versions of choo applications to live together and share the same plugins and/or environment.

## App authors

```js
import choo form 'choo'

const app = choo()
console.log(app.version)
// => 3.3.0
```

## Plugin authors

```js
function onInit(app) {
  console.log(app.version)
  // => 3.3.0
}
```

**Comment by yoshuawuyts** [comment]
in choo v5 `.mount()` is picky on what it accepts

---
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
