### ISSUE TITLE
Wrapping effects with plugins can break internal models

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#368]
@yoshuawuyts pointed this out in IRC as a known bug, but I didn't see an issue for it so I thought I'd make one. If you use `app.use()` to `wrapEffects`, reducers, subscriptions, etc. and change them significantly (ie. order of params, what the params are, etc.), the built-in model's effects/reducers/subscripts (like `setLocation` and `href` anchor spying) will break.

I posted this here instead of in barracks because I imagine barracks is doing its job.

In the meantime, you can do something like this as a hacky workaround:

```javascript
app.use({
  wrapEffects: (cb) => {
    if (cb.name === 'setLocation') return cb

    return (state, data, send, done) => {
      // your override
    }
  }
})
```

**Comment by myobie** [comment]
@timwis I am not having this problem.

I created a small example using my promisify plugin which wraps all effects: https://github.com/myobie/test-wrap-choo

The `location:set` seems to work fine and even return a promise just like I had hoped.

Do you have an example where it doesn't work?

**Comment by timwis** [comment]
@myobie have you upgraded to v4? Can't imagine how you're not experiencing it.. I believe @yoshuawuyts experienced the issue as well (and warned me about it before I understood what he was talking about :P)

**Comment by myobie** [comment]
@timwis the example I posted has `^4.0.1` in the `package.json`. While my example works, I think it's simply because of what it's doing that the bug goes unnoticed (the promise is resolved anyway).

It would seem if one wanted to keep compatibility with choo's location model then one would have to not change the arity or order of the arguments to any of the wrapped functions. It also seems that keeping compatibility with versions 3 and 4 would be pretty hard.

@yoshuawuyts the location model is the only internal model for choo. Would it make more sense to extract it as a plugin so that we can potentially not use it or use a different/wrapped version of it?

Wrapping individual models is pretty easy since we can just return a new set of reducers/effect/etc. But `use` fundamentally changes how choo works, so it seems choo cannot provide any default models without making that feature much less useful.

**Comment by yoshuawuyts** [comment]
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
