### ISSUE TITLE
How is OpenCollective working out?

### ISSUE THREAD

**Issue by zeke** [yoshuawuyts/choo#402]
I just came across this: https://opencollective.com/choo -- looks pretty cool!

Curious to know how it's working out.

**Comment by yoshuawuyts** [comment]
It's quite alright - since joining dat I haven't really invested much time
in getting folks to contribute to choo financially. The folks are real nice
tho. Kind of wish there was more options to personalize the opencollective
page b/c rn it doesn't feel like us.. but it's not bad either. Would
recommend!

**Comment by zeke** [comment]
👍  Thanks Yosh
