### ISSUE TITLE
Unbundle the http module?

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#60]
Wanted to get your thoughts on whether the `http` module still makes sense to bundle with choo? As opposed to pointing folks to it in the readme as a "recommended" module. But if you don't need to make http requests, it isn't really relevant for you.

**Comment by ahdinosaur** [comment]
@timwis i think the intention behind bundling `xhr` within `choo` as `choo/http` is for `choo` to be an opinionated grab-bag of what you need for common applications. since the `choo/http` module is separate from the top-level `choo` module, if you don't need to make http requests then you can choose to not `require('choo/http')` and thus your bundle will not include `xhr`, so the only penalty is the minimal time it took to install `xhr` when you installed `choo` (which is not much since `xhr` is tiny). i personally like this approach of grab bag modules, but it is a slight departure from a pure ["batteries not included"](https://github.com/substack/blog/blob/master/node_aesthetic.markdown#batteries-not-included) approach.

**Comment by kristoferjoseph** [comment]
yes, I feel that `choo` should have `http`, but something like `yo-yo` should not.

**Comment by yoshuawuyts** [comment]
Yeah, I'm not overly convinced `http` should be in `choo`, as the framework has evolved slightly - that said: `http` is super staple to most apps so having a strong opinion on how to do it isn't bad I think (e.g. definitely stay away from `Fetch`)

So not too fussed - if people strongly feel it should go, it goes; if that's not the case I reckon it's okay to leave it in as there's no cost to it.

**Comment by timwis** [comment]
> if you don't need to make http requests then you can choose to not require('choo/http') and thus your bundle will not include xhr, so the only penalty is the minimal time it took to install xhr when you installed choo

good point! i can see both sides. I don't feel strongly either way, just wanted to put it out there. Feel free to close the issue unless you think there's more feedback to be had, @yoshuawuyts. Thanks for the responses.

**Comment by yoshuawuyts** [comment]
Hah yeah, think it's alright to keep it for now and close this then. If someone feels strongly about it discussion is def welcome, always welcome to reopen!
