### ISSUE TITLE
Arch question: can you wait async calls?

### ISSUE THREAD

**Issue by sospedra** [yoshuawuyts/choo#70]
So, is there a way to wait until one specific `effect` is done? While awaiting, blocking the other actions?

**Comment by yoshuawuyts** [comment]
Not yet, this is coming in 3.0. There's an open issue for this in https://github.com/yoshuawuyts/choo/issues/34.

Reason why this takes a while is because it requires a full rewrite of the internals, `send()` wasn't quite built to do this. I'm working on this right now, and if all goes well I expect this to work before the end of the week.

I'm closing this issue for now; let's continue the discussion over in #34 :sparkles: :grin:
