### ISSUE TITLE
subsequent render breaks google map

### ISSUE THREAD

**Issue by knownasilya** [yoshuawuyts/choo#94]
So at first I thought it was an issue with `on-load`, but I realized that Google Maps supports using an element not yet in the DOM..

Ok, so I have an example here where subsequent rerenders break the map: https://github.com/knownasilya/pizza-locator/blob/gh-pages/components/google-map.js#L13

To reproduce:
1. visit https://knownasilya.github.io/pizza-locator/
2. click "closest locations"

Map disappears on second render..

Looks like the element doesn't get updated properly the second time. Any thoughts?

**Comment by toddself** [comment]
First of all, this is a fantastic project because :pizza: === life.

Second... diving in :)

**Comment by toddself** [comment]
I can't run this locally - the API key is not set up for it, but it looks like the map is actually there -- just not displaying.

This is possibly due to the fact that you're triggering the resize event (https://github.com/knownasilya/pizza-locator/blob/gh-pages/components/google-map.js#L38) _before_ the view is re-rendered.

I know google maps is a little picky about this.  Suggest wrapping that in a short-lived `window.setTimeout` call (like 5ms or so) so that it's rendered and triggered?

**Comment by toddself** [comment]
Oops accidentally closed :)

**Comment by knownasilya** [comment]
You should be able to run locally with port 8000, `npm start` && `npm run watch`

**Comment by knownasilya** [comment]
Use `localhost:8000` instead.

**Comment by knownasilya** [comment]
I added a timeout, but nothing. You are correct, the map does load but something is still wrong since it doesn't load any tiles..

**Comment by toddself** [comment]
It's been a few years since I've played with the maps API.  I notice you're making a new map on each call -- every time I've worked with Google Maps I've always just called `new` once for the page, no matter what I was changing/updating.

Let me give that a shot locally

**Comment by knownasilya** [comment]
Good point, I usually do the same.. not sure why I did otherwise..

**Comment by knownasilya** [comment]
Ok, I fixed it with your suggestion. See my latest commit.

**Comment by toddself** [comment]
Awesome!

Yeah, the google maps API is a bit odd sometimes, but this is great :)
